[phases.setup]
nixPkgs = ["gcc", "gnumake", "python310", "python310Packages.pip", "ta-lib"]

[phases.build]
commands = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
command = "uvicorn app:app --host 0.0.0.0 --port 8000"
